name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: [ "enhancement" ]
assignees: StrableD
body:
  - type: textarea
    attributes:
      label: Related Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem...
    validations:
      required: true

  - type: textarea
    id: solution_description
    attributes:
      label: Solution Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution...
    validations:
      required: true

  - type: textarea
    id: alternatives_description
    attributes:
      label: Alternatives Description
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe the alternatives...

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add additional context...